name: "Add line to PR comment"
description: "Adds new line to PR comment"
inputs:
  text:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: add-comment-on-pr
      shell: bash
      run: |
        if [ -f "./artifacts/pr_comment" ]
        then
        echo $'**There is some errors found by automatic PR checks**' >> ./artifacts/pr_comment
        fi
        echo "${{ inputs.text }}" >> ./artifacts/pr_comment
        echo $'\n' >> ./artifacts/pr_comment