name: Comment on PR

on:
  workflow_run:
    workflows:
      - "PR Updated"
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    name: Comment PR
    steps:
      - name: Download artifacts
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "artifacts"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/artifacts.zip', Buffer.from(download.data));
      - name: Unzip artifacts
        run: |
          unzip artifacts.zip
          echo "PR number:"
          cat ./pr_number
          echo "Comment:"
          cat ./pr_comment
      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var fs = require('fs');
            var pr_number = Number(fs.readFileSync('./pr_number'));
            var pr_comment = String(fs.readFileSync('./pr_comment'));
            if (pr_comment) {
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr_number,
                body: pr_comment
              });
            }
