name: PR Updated

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  pr_updated:
    name: PR Updated
    runs-on: ubuntu-latest
    steps:
    - name: Show PR
      if: github.event.action == 'opened' || github.event.action == 'reopened'
      run: |
        echo "${{ github.event.action }}"
    - name: Show PR1
      run: |
        echo 2
        echo "${{ github.event.action }}"
        
