name: PR Updated

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  pr_updated:
    name: PR Updated
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
    - name: Show PR
      run: |
        echo "${{ github.event.action }}"
        
