name: Process results

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["flake8 Lint"]
    types:
      - completed
      
 jobs:
  upload:
    runs-on: ubuntu-latest
    name: cat result
    steps:
      - name: cat
        run: |
          cat result/flake8
