name: Process results

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["flake8"]
    types:
      - completed
      
jobs:
  upload:
    runs-on: ubuntu-latest
    name: comment
    steps:
      - name: download
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "result"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/result.zip', Buffer.from(download.data));
      - name: unzip
        run: |
          unzip result.zip
          cat ./issue_number
          cat ./flake8_result
      - name: comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var fs = require('fs');
            var issue_number = Number(fs.readFileSync('./issue_number'));
            var flake8_result = String(fs.readFileSync('./flake8_result'));
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: flake8_result
            });
